# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
PP_SECRET: "jozu2xs9nw7wnzt"
ACCESS_TOKEN_SECRET: hxiuz1vjh126kst
